### ISSUE TITLE
please declare environment variable 'SUMO_HOME'

### ISSUE THREAD

**Issue by omgbu** [susomena/PERMIT#1]
Question: 'SUMO_HOME' means sumo_plexe or sumo ?
Thanks!

**Comment by omgbu** [comment]
python version is 2.7 or 3.5?
thank you!!

**Comment by omgbu** [comment]
ImportError: No module named 'sumolib'
i find sumolib in plexe-sumo, why ???

**Comment by susomena** [comment]
Hi, the SUMO_HOME environment variable must point to the plexe-sumo directory (where bin, tools, etc. directories can be found). PERMIT should work with both, Python 2.7 and Python 3.5. If you declare the SUMO_HOME environment variable correctly, sumolib and traci should be found when executing PERMIT.

**Comment by omgbu** [comment]
Thanks. I use Instant Plexe, and export plexe-sumo, but still failed. However, when i use Veins, and export sumo, the error disappeared, but the cfg file was not found. May it mean i need install plexe-sumo again??

**Comment by omgbu** [comment]
In your readme, the link of plexe-sumo is sumo, is it wrong or having some differeces？Thank you!

**Comment by susomena** [comment]
In order to use PERMIT you have to use the plexe-sumo version that can be found in the link of the README (https://github.com/michele-segata/sumo/tree/plexe-sumo-0.32.0). You don't need Veins, PERMIT assumes that wireless communications are perfect.

**Comment by omgbu** [comment]
Thank you very much. I use this version: https://github.com/michele-segata/plexe-sumo.
So, the differce and the problem is this !!?

**Comment by omgbu** [comment]
Ok, thank you, i will try again. And i want to combine PERMIT with omnet to do some research on communication. Could you please give me some advice?

**Comment by susomena** [comment]
If you only need the FCD traces of the vehicles for the communications simulations, then you can use PERMIT and export FCD traces and use them in OMNET (sorry, I don't do research on communications, so I don't know how to do this, but I know that it is possible with Veins). On the other hand, in case you need to simulate intervehicle communications in order to perform the maneuvers, I'm afraid that you would need to redefine the execution of the maneuvers in Veins, since all intervehicle communications are assumed perfect in PERMIT (we don't simulate communications).

**Comment by omgbu** [comment]
All right ~ Thanks again !

**Comment by omgbu** [comment]
Hi, I did "python simulator.py -c plexe_scenario.sumo.cfg", but Error: Could not access configuration 'plexe_scenario.sumo.cfg' and 'Could not connect to TraCI server'. Need your help, thanks!!!

**Comment by omgbu** [comment]
Thank u very much! Error Still occurs. I use the sumo-plexe in Plexe, maybe i need try the version indicated in the PERMIT's repository?

**Comment by omgbu** [comment]
Thank u very much! Error Still occurs. I use the sumo-plexe in Plexe, maybe i need try the version indicated in the PERMIT's repository?

**Comment by susomena** [comment]
Yes, you should use that version (https://github.com/michele-segata/sumo/tree/plexe-sumo-0.32.0). Newer versions of Plexe change some things that break PERMIT.

**Comment by omgbu** [comment]
` File "simulator.py", line 113, in main
    platoon.communicate()
  File "/home/plexe/src/PERMIT/platooning.py", line 143, in communicate
    (l_v, l_a, l_u, l_x, l_y, l_t) = cc.unpack(leader_data)`
I try to print leader_data, find that the number of parameters of leader_data is 9, but (l_v, l_a, l_u, l_x, l_y, l_t) is 6

**Comment by susomena** [comment]
That's weird, because I'm using that Plexe-SUMO version and I don't get any error. I will try again. In that SUMO scenario vehicles only merge. They don't split because none of the vehicles will leave the platoon while the rest remain inside. At the end of the simulation you can see the platoon dissolve (all the vehicles leave the platoon at the same time).

**Comment by omgbu** [comment]
Perhaps because i use the different version of SUMO(http://plexe.car2x.org/download/), thanks a lot, how can i simulate the split and leave ?

**Comment by susomena** [comment]
Yes, it is the SUMO version for sure. In order to use PERMIT, the recommended version is this one:

https://github.com/michele-segata/sumo/tree/plexe-sumo-0.32.0

In order to simulate the split and leave maneuvers you need some vehicles to leave the platoon while the platoon remains formed, for example with an off-ramp. Whenever the route of the vehicles leaving does not coincide with the route of the platoon leader, vehicles will leave the platoon.

**Comment by omgbu** [comment]
Thank you very much for your help. I will try the recommended version. And in Plexe:
http://plexe.car2x.org/download/
It also says the version of SUMO is 0.32.0. If you have time, I am looking forward to your development of a compatible version of the official website. 
Thanks again!

**Comment by anirudhparanjothi** [comment]
Hi,

The link you provided to download Plexe-SUMO is not working. https://github.com/michele-segata/sumo/tree/plexe-sumo-0.32.0

Is there any other way to download Plexe-SUMO 0.32.0?
Looking forward to your reply.

**Comment by omgbu** [comment]
Hi, how can I make cars split? I try to change the route of car4, the car leaves, however, error occurs:
`traci.exceptions.TraCIException: Vehicle 'car4' does not support carFollowModel`
It seems that traci thinks car4 leave the platoon ahead of time.
Can you give me an example of the cfg? Very grateful!!!
Thanks again!

**Comment by susomena** [comment]
Hi, sorry for the late reply, I've been busy trying to fix some problems with the branch of Plexe-SUMO that dissapeared from Michele Segata's repository. Now the required Plexe-SUMO is is another repository. This repository is linked in PERMIT's README.

In order to make cars leave a platoon, they should have a different route than the platoon leader's. I have made an example scenario for this maneuver. The files for this example are the following:

- example.nod.xml:

```xml
<nodes>
	<node id="0" x="0.0" y="0.0"/>
	<node id="1" x="10.0" y="0.0"/>
	<node id="2" x="5010.0" y="0.0"/>
	<node id="3" x="5990.0" y="0.0"/>
	<node id="4" x="6000.0" y="0.0"/>
	<node id="5" x="5750.0" y="-750.0"/>
</nodes>
```

- example.edg.xml:

```xml
<edges>
	<edge id="0to1" from="0" to="1" type="type0"/>
	<edge id="1to2" from="1" to="2" type="type0"/>
	<edge id="2to3" from="2" to="3" type="type1"/>
	<edge id="3to4" from="3" to="4" type="type0"/>
	<edge id="2to5" from="2" to="5" type="type0"/>
</edges>
```

- example.typ.xml:

```xml
<types>
	<type id="type0" numLanes="2" speed="33.33"/>
	<type id="type1" numLanes="2" speed="20.00"/>
</types>
```

- example.con.xml:

```xml
<connections>
	<connection from="0to1" to="1to2" fromLane="0" toLane="0"/>
	<connection from="0to1" to="1to2" fromLane="1" toLane="1"/>
	<connection from="1to2" to="2to3" fromLane="0" toLane="0"/>
	<connection from="1to2" to="2to3" fromLane="1" toLane="1"/>
	<connection from="1to2" to="2to5" fromLane="0" toLane="0"/>
	<connection from="1to2" to="2to5" fromLane="1" toLane="1"/>
	<connection from="2to3" to="3to4" fromLane="0" toLane="0"/>
	<connection from="2to3" to="3to4" fromLane="1" toLane="1"/>
</connections>
```

With these four files you should execute `netconvert -n example.nod.xml -e example.edg.xml -t example.typ.xml -x example.con.xml -o example.net.xml` in order to generate the SUMO network file. The SUMO route file and the configuration file are the following:

- example.rou.xml:

```xml
<routes>
	<vType id="type1">
		<carFollowing-CC tauEngine="0.5" omegaN="0.2" xi="1" c1="0.5" decel="9" lanesCount="4" ccAccel="1.5"/>
	</vType>

	<vType id="type2">
		<carFollowing-CC tauEngine="0.5" omegaN="0.2" xi="1" c1="0.5" decel="9" lanesCount="4" ccAccel="1.5"/>
	</vType>

	<route id="route0" edges="0to1 1to2 2to3"/>
	<route id="route1" edges="0to1 1to2 2to5"/>

	<vehicle id="car0" route="route0" depart="0.0" type="type1" departSpeed="max" departLane="0"/>
	<vehicle id="car1" route="route0" depart="0.2" type="type2" departSpeed="max" departLane="1"/>
	<vehicle id="car2" route="route1" depart="0.4" type="type1" departSpeed="max" departLane="0"/>
	<vehicle id="car3" route="route0" depart="0.6" type="type2" departSpeed="max" departLane="1"/>
	<vehicle id="car4" route="route0" depart="0.8" type="type1" departSpeed="max" departLane="0"/>
	<vehicle id="car5" route="route0" depart="1.0" type="type2" departSpeed="max" departLane="1"/>
</routes>
```

- example.sumo.cfg:

```xml
<configuration>
	<input>
		<net-file value="example.net.xml"/>
		<route-files value="example.rou.xml"/>
	</input>

	<time>
		<step-length value="0.1"/>
	</time>

	<gui_only>
		<start value="true"/>
	</gui_only>
</configuration>
```

This scenario can be simulated using the same command as the one in a previous message. This command was `python simulator.py -c example.sumo.cfg -g -ef 1to2 2to3 -vf type1 type2 -pl 8`. I can simulate this scenario without errors.

**Comment by SRazmiRad** [comment]
Hi,

The link you provided to download Plexe-SUMO is not working. https://github.com/michele-segata/sumo/tree/plexe-sumo-0.32.0

Is there any other way to download Plexe-SUMO 0.32.0?
Looking forward to your reply.

**Comment by susomena** [comment]
Hi,

If you check the link in the README of PERMIT, the Michele Segata link is not used anymore. I forked Plexe-SUMO and now the link points to my own Plexe-SUMO repository. The new link is: https://github.com/susomena/plexe-sumo.

**Comment by SRazmiRad** [comment]
I am using the same link you just mentioned. But still, get this error: 
platooning.py", line 143, in communicate
    (l_v, l_a, l_u, l_x, l_y, l_t) = cc.unpack(leader_data)
ValueError: too many values to unpack (expected 6)

**Comment by susomena** [comment]
Have you changed your SUMO_HOME environment variable to the new SUMO location? It seems that it is still pointing to the previous SUMO location. PERMIT should work fine with the Plexe-SUMO version in my repo.

**Comment by SRazmiRad** [comment]
I am a bit confused with SUMO_HOME and Plexe_SUMO. Once I set my environment variable by appending ";C:\Program Files\sumo-1.6.0\bin" to the path according to the instructions here: https://sumo.dlr.de/docs/Basics/Basic_Computer_Skills.html
Should I change it again to use Plexe_SUMO?

**Comment by susomena** [comment]
Yes, anytime you use a different SUMO version you have to change the SUMO_HOME environment variable to point to the location of the SUMO version you want to use.

**Comment by SRazmiRad** [comment]
I did so:
- Cloned Plexe_SUMO from your repo;
- Set SUMO_HOME: changed the path of the environment variable to the route of the Plexe_SUMO folder and also set the same directory as the value of SUMO_HOME variable.
But I still get the same error: 
platooning.py", line 143, in communicate
    (l_v, l_a, l_u, l_x, l_y, l_t) = cc.unpack(leader_data)
ValueError: too many values to unpack (expected 6)
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

**Comment by susomena** [comment]
If you still get that error then your SUMO_HOME variable is not pointing to the correct folder. I just tested it in my computer and it works fine. Are you compiling the Plexe-SUMO version from my repo? Or you are just cloning it?

**Comment by SRazmiRad** [comment]
Just cloned it.

**Comment by susomena** [comment]
There you have it, the repo only contains code, you have to compile it before you can use it. I guess you cloned the repo in the same directory as another SUMO version, then, you always had the same SUMO executable.

**Comment by SRazmiRad** [comment]
I tried to follow the instruction (https://sumo.dlr.de/docs/Installing/Windows_Build.html#doing_everything_inside_visual_studio_2017_or_later) to compile the codes using Visual Studio 2019. But when downloading SUMOlibraries it fails since it finds a virus! Not sure if I am following the right instruction though!

**Comment by susomena** [comment]
I have never compiled SUMO in Windows, so I cannot help you with that. However, those libraries are uploaded to GitHub by DLR, so they shoul be free of viruses. That link with instructions for building SUMO in Windows are the official instructions, so you are right.

**Comment by SRazmiRad** [comment]
This is very strange. I tried to clone SUMO libraries using Git webpage, Git desktop, and also Visual Studio. All of them failed because of the virus (Trojan.TR/Patched.Gen) and the system deletes everything as soon as it finds the virus. 
Anyway, thanks for the explanations.

**Comment by susomena** [comment]
I recommend to use Linux for SUMO if you can. SUMO compilation is easier in Linux and it is the operastive system I used for developing PERMIT, so it should work.

**Comment by lcipolina** [comment]
> 
> 
> Hi, how can I make cars split? I try to change the route of car4, the car leaves, however, error occurs:
> `traci.exceptions.TraCIException: Vehicle 'car4' does not support carFollowModel`
> It seems that traci thinks car4 leave the platoon ahead of time.
Hi @omgbu I am having the same issue. 

Where you ever able to make this library work?
Thanks!

**Comment by Shubham7234** [comment]
hey!, i am getting this error
plexe-sumo-master (1)/plexe-sumo-master/platooning.py", line 142, in communicate
    (l_v, l_a, l_u, l_x, l_y, l_t) = cc.unpack(leader_data)
ValueError: need more than 0 values to unpack
![Screenshot from 2021-10-15 00-34-17](https://user-images.githubusercontent.com/92546857/137382434-6122ccc3-aded-4289-bc6b-7dfbc8b54e54.png)

how to resolve it.

**Comment by mcu-master** [comment]
> I did so:
> 
> * Cloned Plexe_SUMO from your repo;
> * Set SUMO_HOME: changed the path of the environment variable to the route of the Plexe_SUMO folder and also set the same directory as the value of SUMO_HOME variable.
>   But I still get the same error:
>   platooning.py", line 143, in communicate
>   (l_v, l_a, l_u, l_x, l_y, l_t) = cc.unpack(leader_data)
>   ValueError: too many values to unpack (expected 6)
>   Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
>   Quitting (on error).

I also encountered the same problem, did you solve it?

**Comment by mcu-master** [comment]
I also encountered the same problem, 
I get the same error:
>   platooning.py", line 143, in communicate
>   (l_v, l_a, l_u, l_x, l_y, l_t) = cc.unpack(leader_data)
>   ValueError: too many values to unpack (expected 6)
>   Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
>   Quitting (on error).
